import { DataClass, Report } from "@seasketch/geoprocessing";

/**
 * Area of ocean within eez minus land in square miles. Calculated by drawing
 * sketch in seasketch project, exporting the resulting sketch, calling turf/area function on it and converting square
 * meters to square miles */
export const STUDY_REGION_AREA_SQ_METERS = undefined;

export const units = "metric";

export const localDataUrl = `http://127.0.0.1:8080/`;
export const dataBucketUrl =
  process.env.NODE_ENV === "test"
    ? localDataUrl
    : `https://gp-nz-national-reports-datasets.s3.ap-southeast-2.amazonaws.com/`;

export const cogFileSuffix = "_cog.tif";
export const fgbFileSuffix = ".fgb";

//// OBJECTIVES ////

export const objectives = {};

//// HABITAT PROTECTION ////

// Multi-class raster (categorical)
const sccClasses: DataClass[] = Array.from({ length: 75 }, (v, i) => ({
  numericClassId: i,
  classId: `Group ${i}`,
  display: `Group ${i}`,
}));

const sccHabitat: Report = {
  reportId: "sccHabitat",
  metrics: {
    areaOverlap: {
      metricId: "areaOverlap",
      baseFilename: "SCC_GF75_250m_merged_east180",
      filename: `SCC_GF75_250m_merged_east180${cogFileSuffix}`,
      classes: sccClasses,
      layerId: "",
    },
  },
};

const hgmspHabitat: Report = {
  reportId: "hgmspHabitat",
  metrics: {
    areaOverlap: {
      metricId: "areaOverlap",
      baseFilename: "HGMSP_Habitats_2021",
      filename: `HGMSP_Habitats_2021${cogFileSuffix}`,
      classProperty: "Habitat",
      classes: [
        // generated by hgmsp-habitat-gen-classes
        {
          classId: "Moderate Deep Rocky Reef",
          display: "Moderate Deep Rocky Reef",
        },
        {
          classId: "Moderate Upper Slope Mud",
          display: "Moderate Upper Slope Mud",
        },
        {
          classId: "Moderate Deep Sand",
          display: "Moderate Deep Sand",
        },
        {
          classId: "Moderate Deep Mud",
          display: "Moderate Deep Mud",
        },
        {
          classId: "Moderate Intertidal Rocky Reef",
          display: "Moderate Intertidal Rocky Reef",
        },
        {
          classId: "Sheltered Deep Rocky Reef",
          display: "Sheltered Deep Rocky Reef",
        },
        {
          classId: "Very Sheltered Intertidal Rocky Reef",
          display: "Very Sheltered Intertidal Rocky Reef",
        },
        {
          classId: "Very Sheltered Shallow Rocky Reef",
          display: "Very Sheltered Shallow Rocky Reef",
        },
        {
          classId: "Moderate Shallow Sand",
          display: "Moderate Shallow Sand",
        },
        {
          classId: "Moderate Shallow Rocky Reef",
          display: "Moderate Shallow Rocky Reef",
        },
        {
          classId: "Sheltered Intertidal Rocky Reef",
          display: "Sheltered Intertidal Rocky Reef",
        },
        {
          classId: "Sheltered Shallow Sand",
          display: "Sheltered Shallow Sand",
        },
        {
          classId: "Sheltered Shallow Rocky Reef",
          display: "Sheltered Shallow Rocky Reef",
        },
        {
          classId: "Sheltered Intertidal Soft Sediment",
          display: "Sheltered Intertidal Soft Sediment",
        },
        {
          classId: "Very Sheltered Shallow Sand",
          display: "Very Sheltered Shallow Sand",
        },
        {
          classId: "Moderate Deep Gravel",
          display: "Moderate Deep Gravel",
        },
        {
          classId: "Sheltered Deep Sand",
          display: "Sheltered Deep Sand",
        },
        {
          classId: "Very Sheltered Intertidal Soft Sediment",
          display: "Very Sheltered Intertidal Soft Sediment",
        },
        {
          classId: "Moderate Shallow Gravel",
          display: "Moderate Shallow Gravel",
        },
        {
          classId: "Sheltered Shallow Gravel",
          display: "Sheltered Shallow Gravel",
        },
        {
          classId: "Estuarine Intertidal Soft Sediment",
          display: "Estuarine Intertidal Soft Sediment",
        },
        {
          classId: "Estuarine Shallow Sand",
          display: "Estuarine Shallow Sand",
        },
        {
          classId: "Estuarine Intertidal Rocky Reef",
          display: "Estuarine Intertidal Rocky Reef",
        },
        {
          classId: "High Current Shallow Sand",
          display: "High Current Shallow Sand",
        },
        {
          classId: "Estuarine Shallow Mud",
          display: "Estuarine Shallow Mud",
        },
        {
          classId: "Estuarine Shallow Rocky Reef",
          display: "Estuarine Shallow Rocky Reef",
        },
        {
          classId: "Very Sheltered Deep Sand",
          display: "Very Sheltered Deep Sand",
        },
        {
          classId: "Very Sheltered Deep Rocky Reef",
          display: "Very Sheltered Deep Rocky Reef",
        },
        {
          classId: "High Current Intertidal Soft Sediment",
          display: "High Current Intertidal Soft Sediment",
        },
        {
          classId: "High Current Intertidal Rocky Reef",
          display: "High Current Intertidal Rocky Reef",
        },
        {
          classId: "High Current Shallow Rocky Reef",
          display: "High Current Shallow Rocky Reef",
        },
        {
          classId: "High Current Deep Sand",
          display: "High Current Deep Sand",
        },
        {
          classId: "Sheltered Shallow Mud",
          display: "Sheltered Shallow Mud",
        },
        {
          classId: "Sheltered Deep Mud",
          display: "Sheltered Deep Mud",
        },
        {
          classId: "Moderate Shallow Mud",
          display: "Moderate Shallow Mud",
        },
        {
          classId: "Moderate Mid-slope Mud",
          display: "Moderate Mid-slope Mud",
        },
        {
          classId: "Moderate Upper Slope Sand",
          display: "Moderate Upper Slope Sand",
        },
        {
          classId: "High Current Deep Rocky Reef",
          display: "High Current Deep Rocky Reef",
        },
        {
          classId: "Sheltered Deep Gravel",
          display: "Sheltered Deep Gravel",
        },
        {
          classId: "High Current Shallow Gravel",
          display: "High Current Shallow Gravel",
        },
        {
          classId: "Very Sheltered Shallow Gravel",
          display: "Very Sheltered Shallow Gravel",
        },
        {
          classId: "High Current Deep Gravel",
          display: "High Current Deep Gravel",
        },
        {
          classId: "High Current Deep Mud",
          display: "High Current Deep Mud",
        },
        {
          classId: "Very Sheltered Shallow Mud",
          display: "Very Sheltered Shallow Mud",
        },
        {
          classId: "Very Sheltered Deep Mud",
          display: "Very Sheltered Deep Mud",
        },
        {
          classId: "Very Sheltered Deep Gravel",
          display: "Very Sheltered Deep Gravel",
        },
        {
          classId: "High Current Shallow Mud",
          display: "High Current Shallow Mud",
        },
      ],
      layerId: "",
    },
  },
};

export default {
  STUDY_REGION_AREA_SQ_METERS,
  units,
  localDataUrl,
  dataBucketUrl,
  objectives,
  reports: {
    sccHabitat,
    hgmspHabitat,
  },
};
